spring:
  application:
    name: inventory-reservation-benchmark

  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  data:
    redis:
      host: localhost
      port: ${REDIS_PORT}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
