global:
  scrape_interval: 15s

scrape_configs:
  - job_name: inventory-reservation-benchmark
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - inventory-reservation-benchmark:8080
